# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bc4bdea2bf33f1add154fae969b4858020ec50bcea7037dab9fa52989dce69102e4d5f2e4ab3db7f060a6c13a538a3db5e143c227485845906bf32495de78d9

test:
  secret_key_base: 0573dab5189f1caa633c6bd422352fa050f2a409ff4ff1321ff0a4cbcd497116ea7168b7d80a556b783e6c8f79a58ce3c56acdd842042d5e506a78acf0d78f15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
